Added a configuration log
./configure now generates a configuration log, along with performing some basic tests to see if all programs are where we expect them

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# CONFIGURE SCRIPT FOR BUILD SYSTEM - v0.0
+# CONFIGURE SCRIPT FOR BUILD SYSTEM - v0.1
 #
 # Script to configure our build environment (sets some variables, lets us define
 # some parameters about our build). Run this before any makefiles (trying to run
@@ -12,7 +12,7 @@
 #
 # 2019 Diogo Gomes
 
-scriptversion="0.0"
+scriptversion="0.1"
 
 # ------------------------------------------------------------------------------
 # Functions
@@ -22,12 +22,31 @@ function help {
     echo "Work in progress"
 }
 
+function target_arch {
+    if echo "$1" | grep -Eq 'i[[:digit:]]86-'; then
+        echo i386;
+    else
+        echo "$1" | grep -Eo '^[[:alnum:]_]*';
+    fi
+}
+
+function log_header {
+    echo ""
+    echo ""
+    echo "###################################################"
+    echo ""
+    echo "$1"
+    echo ""
+    echo "###################################################"
+}
+
 # ------------------------------------------------------------------------------
 # Defaults
 # These are the default values for our build variables
 # ------------------------------------------------------------------------------
 
 target=i686-elf # TODO: add targetarch
+targetarch=$(target_arch ${target})
 
 # Directories
 rootsrcdir=$(pwd)
@@ -131,6 +150,108 @@ for arg in "$@"; do
 done
 
 # ------------------------------------------------------------------------------
+# Checking whether we have everything we expect to build the project
+# Then generate a config.log
+# ------------------------------------------------------------------------------
+
+configlog=config.log
+
+echo "CONFIGURATION LOG" > ${configlog}
+echo "" >> ${configlog}
+echo "Generated by configure version ${scriptversion}" >> ${configlog}
+echo "" >> ${configlog}
+echo "INVOCATION = $0 $@" >> ${configlog}
+echo "DATE = $(date)" >> ${configlog}
+echo "" >> ${configlog}
+echo "PLATFORM---------" >> ${configlog}
+echo "hostname = $(hostname)" | tee -a ${configlog}
+echo "Machine Hardware (uname -m) = $(uname -m)" | tee -a ${configlog}
+echo "Kernel Release (uname -r) = $(uname -r)" | tee -a ${configlog}
+echo "Kernel Name (uname -s) = $(uname -n)" | tee -a ${configlog}
+echo "Kernel Version (uname -v) = $(uname -v)" | tee -a ${configlog}
+echo "" >> ${configlog}
+
+printf 'Checking whether CC compiler is present ...'
+log_header CC >> ${configlog}
+if ${cc} -v &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: CC compiler not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether CXX compiler is present ...'
+log_header CXX >> ${configlog}
+if ${cxx} -v &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: CXX compiler not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether AR is present ...'
+log_header AR >> ${configlog}
+if ${ar} --version &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: AR not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether AS is present ...'
+log_header AS >> ${configlog}
+if ${ar} --version &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: AS not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether xorriso is present ...'
+log_header xorriso >> ${configlog}
+if xorriso --version &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: xorriso not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether ISOTOOL is present ...'
+log_header ISOTOOL >> ${configlog}
+if ${isotool} --version &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: ISOTOOL not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking whether qemu-system-${targetarch} is present ...'
+log_header qemu-system-${targetarch} >> ${configlog}
+if qemu-system-${targetarch} --version &>> ${configlog}; then
+    printf ' yes\n'
+else
+    printf ' no\n'
+    echo 'Error: qemu-system-${targetarch} not found' | tee -a ${configlog}
+    exit 2
+fi
+
+printf 'Checking make version ...'
+log_header MAKE >> ${configlog}
+if make --version &>> ${configlog}; then
+    printf ' done\n'
+else
+    printf ' no\n'
+    echo 'Error: make not found' | tee -a ${configlog}
+    exit 2
+fi
+
+# ------------------------------------------------------------------------------
 # Generating the build files
 # ------------------------------------------------------------------------------
 
@@ -139,7 +260,7 @@ makefiles=`find . -name Makefile.in | sed 's/.in//'`
 makeconfig=config/make/config.mk
 outputconfig=config/make/output.mk.in
 
-echo "generating ${makeconfig} ..."
+echo "Generating ${makeconfig} ..."
 
 # Header of the file
 echo "# MAIN CONFIGURATION FILE FOR MAKEFILE" > ${makeconfig}
@@ -150,6 +271,7 @@ echo "override SHELL:=/bin/sh" >> ${makeconfig}
 
 # Writing configs to file
 echo "TARGET:=${target}" >> ${makeconfig}
+echo "TARGETARCH:=${targetarch}" >> ${makeconfig}
 echo "ROOT_SRCDIR:=${rootsrcdir}" >> ${makeconfig}
 echo "AR=${ar}" >> ${makeconfig}
 echo "AS=${as}" >> ${makeconfig}
@@ -175,6 +297,8 @@ echo "LIBS:= ${libs}" >> ${makeconfig}
 
 echo "MADE_CONFIG:=true" >> ${makeconfig}
 
+echo "MAKECONFIG:=${makeconfig}" >> ${makeconfig}
+
 # Writing end of autofile comment
 echo "# ------------------------------------------------------------------------------" >> ${makeconfig}
 echo "# End of autoconfigured file" >> ${makeconfig}
@@ -193,4 +317,36 @@ for name in ${makefiles}; do
     cat ${name}.in >> $name
 done
 
-echo 'configuration complete, type make to build.'
+# Writing make variables to config.log
+printf '\n\n\nMAKE VARIABLES---------\n' >> ${configlog}
+echo "override SHELL:=/bin/sh" >> ${configlog}
+echo "TARGET:=${target}" >> ${configlog}
+echo "TARGETARCH:=${targetarch}" >> ${configlog}
+echo "ROOT_SRCDIR:=${rootsrcdir}" >> ${configlog}
+echo "AR=${ar}" >> ${configlog}
+echo "AS=${as}" >> ${configlog}
+echo "CC=${cc}" >> ${configlog}
+echo "CXX=${cxx}" >> ${configlog}
+echo "ISOTOOL:=${isotool}" >> ${configlog}
+echo "ISOCHECKTOOL:=${isochecktool}" >> ${configlog}
+echo "SYSROOT:=${sysroot}" >> ${configlog}
+echo "PREFIX?=${prefix}" >> ${configlog}
+echo "EXEC_PREFIX?=${execprefix}" >> ${configlog}
+echo "BOOTDIR?=${bootdir}" >> ${configlog}
+echo "LIBDIR?=${libdir}" >> ${configlog}
+echo "INCLUDEDIR?=${includedir}" >> ${configlog}
+if $debugsym; then
+    echo "CFLAGS:= ${cflags} -g" >> ${configlog}
+    echo "CXXFLAGS:= ${cxxflags} -g" >> ${configlog}
+else
+    echo "CFLAGS:= ${cflags}" >> ${configlog}
+    echo "CXXFLAGS:= ${cxxflags}" >> ${configlog}
+fi
+echo "LDFLAGS:= ${ldflags}" >> ${configlog}
+echo "LIBS:= ${libs}" >> ${configlog}
+echo "MADE_CONFIG:=true" >> ${configlog}
+echo "MAKECONFIG:=${makeconfig}" >> ${configlog}
+
+
+
+echo 'Configuration complete, type make to build.'
